[package]
name = "fixture-runtime-service"
version = "0.0.0"
edition = "2021"

[package.metadata.agentmod]
kind = "process-layer"
process = "runtime"
layer = "service"

[dependencies]
fixture-runtime-data = { version = "0.1.0", path = "../data" }
fixture-harness-logic = { version = "0.1.0", path = "../../harness/logic" }
